[chisel] implement a new elaborator with `PanamaCIRCTConverter`
chipsalliance/t1 pull request #319
Opened 2023-09-13 20:52 UTC by SpriteOvO

2024-01-01 07:14 UTC, SpriteOvO commented
Run command `nix build .#t1.v1024-l8-b2.elaborate-binder` to check the results produced by Chisel Binder framework.

2024-01-01 07:15 UTC, SpriteOvO commented
CC @sequencer for review, thanks.

2024-01-04 04:59 UTC, sequencer requested changes

2024-01-04 04:59 UTC, sequencer commented on build.sc
> +import $file.dependencies.chisel.common
Don't introduce common.

2024-01-04 04:59 UTC, sequencer commented on build.sc
> +  extends millbuild.common.ElaboratorModule with millbuild.dependencies.chisel.common.HasCIRCTPanamaBinderModule {
vendor a `HasCIRCTPanamaBinderModule` in our own `common.sc`

2024-01-04 04:59 UTC, sequencer commented on elaborator/src/Main.scala
> +    @arg(name = "binder") binder: Boolean) {
```suggestion
    @arg(name = "binder", short = 'b') binder: Boolean) {
```

2024-01-04 04:59 UTC, sequencer commented on elaborator/src/Main.scala
> +            converter.exportSplitVerilog(dir_)
?

2024-01-17 20:26 UTC, closed without merging