refactor decoder to use rvdecoderdb
chipsalliance/t1 pull request #430
Opened 2024-01-25 09:32 UTC by Lucas-Wye

- remove the operations of reading inst-table.adoc
- using API from rvdecoderdb

2024-01-26 09:13 UTC, sequencer commented on build.sc
>    def chiselModule = Some(chisel)
No cde in t1

2024-01-26 09:15 UTC, sequencer commented on t1/src/decoder/Decoder.scala
> +
Nit don’t add space here

2024-02-02 09:37 UTC, sequencer commented on t1/src/decoder/Decoder.scala
> +    val expandedOps: Array[Op] = (instructions.filter(_.encoding.toString.substring(32-6-1, 32-0) == opVOpcode).map{ insn =>
Kinda dirty... but OK...

2024-02-02 09:37 UTC, sequencer commented on t1/src/decoder/Decoder.scala
> +            .replace("vnsrl.w", "vnsrl")
oh my god

2024-02-04 17:33 UTC, sequencer commented on t1/src/decoder/Decoder.scala
> +    "FF" -> "101"
OPCFG is missed, and please add documentation for these functions, give reference link and **align** to specification:
e.g.
```suggestion
    // Refer to [https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#101-vector-arithmetic-instruction-encoding].
    "OPIVV" -> "000",
    "OPFVV" -> "001",
    "OPMVV" -> "010",
    "OPIVI" -> "011",
    "OPIVX" -> "100",
    "OPFVF" -> "101",
    "OPMVX" -> "110",
    "OPCFG" -> "111",
```

2024-02-04 17:33 UTC, sequencer commented on t1/src/decoder/Decoder.scala
> +      // TODO[0]: ? for vm
finish this TODO?

2024-02-04 17:33 UTC, sequencer commented on t1/src/decoder/Decoder.scala
> +  def bitPat: BitPat = if (notLSU) BitPat(
Please add doc to this function

2024-02-04 17:33 UTC, sequencer commented on t1/src/decoder/Decoder.scala
> +  private val opfvfFunct3 = "101"
Dup code?

2024-02-05 01:57 UTC, Lucas-Wye commented on t1/src/decoder/Decoder.scala
> +  private val opfvfFunct3 = "101"
already replaced with better name

2024-02-06 02:50 UTC, sequencer requested changes

2024-02-14 15:09 UTC, sequencer approved these changes

2024-02-15 03:18 UTC, merged