[script] replace python script with scala
chipsalliance/t1 pull request #492
Opened 2024-03-29 12:38 UTC by Avimitin

This PR add a new Scala executable t1-helper to replace the run-test.py script.

2024-03-29 17:01 UTC, sequencer requested changes

2024-03-30 10:50 UTC, sequencer requested changes
For scala3, I prefer removing brackets for making it more python-like

2024-03-30 10:50 UTC, sequencer commented on build.sc
> +  val scala3 = "3.3.3"
this is unused

2024-03-30 16:07 UTC, Avimitin commented
Please review the latest coding style.

2024-03-30 16:14 UTC, sequencer reviewed
Do it in a Scala3(python) way :)

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +}
```suggestion
object Logger:
  def info(message: String) = println(s"${BOLD}${GREEN}[INFO]${RESET} ${message}")
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  ): os.Path = {
```suggestion
  ): os.Path =
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  }
```suggestion
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  ): os.Path = {
```suggestion
  ): os.Path =
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  }
```suggestion
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  ): os.Path = {
```suggestion
  ): os.Path =
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  }
```suggestion
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  ): os.Path = {
```suggestion
  ): os.Path =
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  }
```suggestion
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  ) = {
```suggestion
  ) =
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  }
```suggestion
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  ) = {
```suggestion
  ) =
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  }
```suggestion
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  @main def listConfig() = {
```suggestion
  @main def listConfig() =
```

2024-03-30 16:14 UTC, sequencer commented on script/src/Main.scala
> +  }
```suggestion
```

2024-03-30 17:03 UTC, Avimitin commented
No I think it is more like [Ruby](https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html#the-end-marker-1), but better.

2024-03-30 18:06 UTC, sequencer approved these changes
In the next PR, we should remove original python script ;p

2024-03-30 18:06 UTC, merged