[RFC] emulation devices for t1rocket
chipsalliance/t1 pull request #800
Opened 2024-10-14 15:35 UTC by OceanS2000

Add extensible devices emulation for t1rocket simulation dpi backend. Currently only simple Memory device is implemented, and more devices with more functionality are expected to come.

2024-10-15 02:04 UTC, FanShupei requested changes

2024-10-15 13:05 UTC, OceanS2000 commented on difftest/dpi_t1rocket/src/bus.rs
> +  pub fn read_mem_axi(&self, addr: u32, size: u32, bus_size: u32) -> Vec<u8> {
done

2024-10-15 13:05 UTC, OceanS2000 commented on difftest/dpi_t1rocket/src/bus.rs
> +  pub fn write_mem_axi(
done

2024-10-15 13:15 UTC, OceanS2000 commented on difftest/dpi_t1rocket/src/bus/mem.rs
> +}
indirection it goes, then. This should avoid big stack allocation while still convey that `mem` shall be a fixed-size array.

2024-10-23 10:59 UTC, FanShupei commented
LGTM

2024-10-23 11:08 UTC, sequencer approved these changes

2024-10-23 11:08 UTC, merged